apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaticy-cluster-viewer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaticy-cluster-role
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - events
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - pods/log
      - secrets
      - serviceaccounts
      - services
      - namespaces
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    resourceNames: ["vaticy-cluster-viewer"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-vaticy-cluster-viewer-to-vaticy-cluster-role
subjects:
- kind: ServiceAccount
  name: vaticy-cluster-viewer
  namespace: default
roleRef:
  kind: ClusterRole
  name: vaticy-cluster-role
  apiGroup: rbac.authorization.k8s.io